### PR TITLE
Switch to FD0 22.08

### PR DESCRIPTION
**Pull request by bbhtt**
Please ignore 3962c30c8fb8db3aa879956f71cc4314e67629cd

### CODE REVIEW

**Comment by bbhtt** [comment]
> Started [test build 112849](https://buildbot.flathub.org/#/builders/32/builds/112849)

```
file-chooser.cpp: In member function ‘virtual void utsushi::gtkmm::file_chooser::on_response(int)’:
file-chooser.cpp:271:13: error: the address of ‘Gtk::Dialog::<anonymous>’ will never be NULL [-Werror=address]
  271 |         if (dynamic_cast< Gtk::Window * > (this))
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from file-chooser.hpp:24,
                 from file-chooser.cpp:25:
/app/include/gtkmm-2.4/gtkmm/dialog.h:125:7: note: ‘Gtk::Dialog::<anonymous>’ declared here
  125 | class Dialog : public Window
      |       ^~~~~~
file-chooser.cpp:296:15: error: the address of ‘Gtk::Dialog::<anonymous>’ will never be NULL [-Werror=address]
  296 |           if (dynamic_cast< Gtk::Window * > (this))
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/app/include/gtkmm-2.4/gtkmm/dialog.h:125:7: note: ‘Gtk::Dialog::<anonymous>’ declared here
  125 | class Dialog : public Window
      |       ^~~~~~
file-chooser.cpp:349:7: error: the address of ‘Gtk::Dialog::<anonymous>’ will never be NULL [-Werror=address]
  349 |   if (dynamic_cast< Gtk::Window * > (this))
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/app/include/gtkmm-2.4/gtkmm/dialog.h:125:7: note: ‘Gtk::Dialog::<anonymous>’ declared here
  125 | class Dialog : public Window
      |       ^~~~~~
cc1plus: all warnings being treated as errors
```

https://gitlab.com/utsushi/utsushi/-/issues/113

**Comment by hfiguiere** [comment]
I was looking at actually switching to 22.08 Freedesktop because this doesn't use anything from the GNOME platform. It's not even gtk3.

**Comment by hfiguiere** [comment]
adding 
```json
                    "build-options": {
                        "cxxflags": "-Wno-error=address"
                    },
```
to the utsushi module should fix this

**Comment by bbhtt** [comment]
> I was looking at actually switching to 22.08 Freedesktop because this doesn't use anything from the GNOME platform. It's not even gtk3.

Ok, I can check that.

> to the utsushi module should fix this

SUSE has a patch for it I'll add it (they don't carry authorship so I can't apply that)

**Comment by hfiguiere** [comment]
no need for a patch.  Just setting cxxflags ought to be enough. maybe just `-Wno-error`.

**Comment by bbhtt** [comment]
> no need for a patch. Just setting cxxflags ought to be enough. maybe just `-Wno-error`.

Ok added.

**Comment by bbhtt** [comment]
> Started [test build 112859](https://buildbot.flathub.org/#/builders/32/builds/112859)

Another warning:

```
In file included from /app/include/boost/config/header_deprecated.hpp:18,
                 from /app/include/boost/spirit/include/phoenix_container.hpp:11,
                 from grammar-formats.ipp:50,
                 from grammar-formats.cpp:29:
/app/include/boost/spirit/include/phoenix_container.hpp:12:1: note: ‘#pragma message: This header is deprecated. Use <boost/phoenix/stl/container.hpp> instead.’
   12 | BOOST_HEADER_DEPRECATED("<boost/phoenix/stl/container.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
/app/include/boost/spirit/include/phoenix_operator.hpp:12:1: note: ‘#pragma message: This header is deprecated. Use <boost/phoenix/operator.hpp> instead.’
   12 | BOOST_HEADER_DEPRECATED("<boost/phoenix/operator.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from point.hpp:24,
                 from bounding-box.hpp:24,
                 from get-extended-identity.hpp:27,
                 from extended-scanner.hpp:29,
                 from extended-scanner.cpp:44:
vector.hpp: In instantiation of ‘utsushi::_drv_::esci::vector<T, size_>& utsushi::_drv_::esci::vector<T, size_>::operator/=(const T&) [with T = utsushi::quantity; long unsigned int size_ = 2]’:
/app/include/boost/operators.hpp:271:1:   required from ‘utsushi::_drv_::esci::vector<utsushi::quantity, 2> boost::operators_impl::operator/(const utsushi::_drv_::esci::vector<utsushi::quantity, 2>&, const utsushi::quantity&)’
extended-scanner.cpp:1308:72:   required from here
vector.hpp:92:36: error: ‘std::binder2nd<_Operation> std::bind2nd(const _Operation&, const _Tp&) [with _Operation = divides<utsushi::quantity>; _Tp = utsushi::quantity]’ is deprecated: use 'std::bind' instead [-Werror=deprecated-declarations]
   92 |                       std::bind2nd (std::divides<T> (), t));
      |                       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12.1.0/bits/stl_function.h:1438,
                 from /usr/include/c++/12.1.0/string:48,
                 from /usr/include/c++/12.1.0/bits/locale_classes.h:40,
                 from /usr/include/c++/12.1.0/bits/ios_base.h:41,
                 from /usr/include/c++/12.1.0/streambuf:41,
                 from /usr/include/c++/12.1.0/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/12.1.0/iterator:66,
                 from /app/include/boost/iterator/iterator_traits.hpp:10,
                 from /app/include/boost/range/mutable_iterator.hpp:23,
                 from /app/include/boost/range/iterator.hpp:20,
                 from /app/include/boost/range/begin.hpp:20,
                 from /app/include/boost/assign/list_inserter.hpp:22,
                 from extended-scanner.cpp:28:
/usr/include/c++/12.1.0/backward/binders.h:172:5: note: declared here
  172 |     bind2nd(const _Operation& __fn, const _Tp& __x)
      |     ^~~~~~~
In file included from /app/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /app/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /app/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /app/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /app/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /app/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /app/include/boost/shared_ptr.hpp:17,
                 from /app/include/boost/date_time/time_clock.hpp:17,
                 from /app/include/boost/date_time/posix_time/posix_time_types.hpp:10,
                 from /app/include/boost/date_time/posix_time/time_formatters.hpp:16,
                 from /app/include/boost/date_time/posix_time/posix_time.hpp:24,
                 from ../../utsushi/log.hpp:24,
                 from grammar.cpp:33:
/app/include/boost/spirit/include/phoenix_operator.hpp:12:1: note: ‘#pragma message: This header is deprecated. Use <boost/phoenix/operator.hpp> instead.’
   12 | BOOST_HEADER_DEPRECATED("<boost/phoenix/operator.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from matrix.hpp:28,
                 from scanner.hpp:29,
                 from compound-scanner.hpp:32,
                 from compound-scanner.cpp:46:
vector.hpp: In instantiation of ‘utsushi::_drv_::esci::vector<T, size_>& utsushi::_drv_::esci::vector<T, size_>::operator*=(const T&) [with T = double; long unsigned int size_ = 3]’:
matrix.hpp:62:32:   required from ‘utsushi::_drv_::esci::matrix<T, rows_, cols_>& utsushi::_drv_::esci::matrix<T, rows_, cols_>::operator*=(const T&) [with T = double; long unsigned int rows_ = 3; long unsigned int cols_ = 3]’
compound-scanner.cpp:119:10:   required from here
vector.hpp:85:36: error: ‘std::binder2nd<_Operation> std::bind2nd(const _Operation&, const _Tp&) [with _Operation = multiplies<double>; _Tp = double]’ is deprecated: use 'std::bind' instead [-Werror=deprecated-declarations]
   85 |                       std::bind2nd (std::multiplies<T> (), t));
      |                       ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/12.1.0/bits/stl_function.h:1438,
                 from /usr/include/c++/12.1.0/string:48,
                 from /usr/include/c++/12.1.0/stdexcept:39,
                 from compound-scanner.cpp:27:
/usr/include/c++/12.1.0/backward/binders.h:172:5: note: declared here
  172 |     bind2nd(const _Operation& __fn, const _Tp& __x)
      |     ^~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by hfiguiere** [comment]
With `-Wno-error` it works. The problem is upstream build by default with -Werror

**Comment by bbhtt** [comment]
> With `-Wno-error` it works.

Yea added.

**Comment by bbhtt** [comment]
Should be ready, just cleaning up the GNOME 43 commits.

**Pull request merged**
